### ISSUE TITLE
Create Docker base image

### ISSUE THREAD

**Issue by david-chau** [gavinz0228/ktvcreator#1]
If you run `docker build` on a new machine, it will take a long time to fetch all of the dependencies for first time.

We can avoid this by moving the core installs to another base image, which is only built / pushed once.
This app can then reference the new base image its Docker file

Example app `Dockerfile`:
```
FROM gavin0228:ktvcreator_base

# Add any specific app configs here
COPY *.py ./
#

EXPOSE 80
CMD ["python3", "-m", "gunicorn", "-w", "4", "-b", "0.0.0.0:80","server:app"]
```

Example base `Dockerfile`
```
FROM ubuntu:20.04
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt
RUN apt update
RUN apt -y install python3.9
RUN apt -y install pip
RUN apt -y install ffmpeg
RUN apt -y install nvidia-cuda-toolkit

EXPOSE 80
CMD ["python3", "-m", "gunicorn", "-w", "4", "-b", "0.0.0.0:80","server:app"]
```

**Comment by Kalpesh-18** [comment]
Can't all of this be done in a single dockerfile using multi stage build, rather than having two dockerfiles?

**Comment by david-chau** [comment]
> Can't all of this be done in a single dockerfile using multi stage build, rather than having two dockerfiles?

My understanding is that if you do that, you would still need to build the first stage locally, which takes a long time to download dep/unpack/install if you have a "new" computer.

If you already have the base image to download on docker hub, you won't need to run the full download dep/unpack/install. You would just need to download the image that has everything.

**Comment by Kalpesh-18** [comment]
Ok so the whole point is to stack up the ubuntu image with all the dependencies in a docker image and use it as new base image, in that case would it be fine if we even install the dependencies in requirement.txt inside the base dockerfile?

**Comment by david-chau** [comment]
Right, that sounds like it should be fine as well.
I believe future modifications would be more on the app config/parameters as opposed to the dependencies

**Comment by Kalpesh-18** [comment]
Yes this can be done, would keep a check on the changes. Thanks
